version: "3"
services:
  coordinator:
    image: basho/riak-kv
    ports:
      - "8087"
      - "8098"
    environment:
      - CLUSTER_NAME=riakkv
    labels:
      - "com.basho.riak.cluster.name=riak-kv"
  member:
    image: basho/riak-kv
    ports:
      - "8087"
      - "8098"
    labels:
      - "com.basho.riak.cluster.name=riak-kv"
    links:
      - coordinator
    depends_on:
      - coordinator
    environment:
      - CLUSTER_NAME=riakkv
      - COORDINATOR_NODE=coordinator

  beanstalk:
    image: schickling/beanstalkd
    ports: 
      - "11300:11300"

  workmanager:
    image: work-manager
    links: 
      - beanstalk
    depends_on:
      - beanstalk
    environment:
      - BEANSTALK=beanstalk
      - RIAKNODE=coordinator

networks:
  default:
    external:
      name: composeTest 
 
